<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Intel8080.Emulator\Intel8080.Emulator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Roms\8080EXM.COM">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Roms\8080PRE.COM">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Roms\CPUTEST.COM">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Roms\TST8080.COM">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
